name: Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "extracted/**"
      - ".github/workflows/pages.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Build
        run: |
          mkdir -p build build/extracted
          touch build/.nojekyll
          cp index.html build/
          cp -R extracted/* build/extracted/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
